version: '3.1'

services:
    webserver:
        image: roccodonnarumma/airflow-gcp:1.8.0-gcp
        restart: always
        volumes:
            - ./iam/:/usr/local/airflow/iam 
        ports:
            - "8080:8080"
        environment:
            - EXECUTOR=Local
            - GCP_PROJECT=gcp-rocco
            - GCP_REGION=us-central1
            - GCP_DATABASE_INSTANCE_NAME=airflow
            - GCS_BUCKET_ID=gcp-rocco
        command: webserver
        #healthcheck:
        #test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        #interval: 30s
        #timeout: 30s
        #retries: 3
